autoOffice/Models/Leave.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;

namespace autoOffice.Models
{
    public enum LeaveApproveStatus{
        Approved=1,
        Reject=2,
        Pending=3
    }
    [Table("rc_Leaves", Schema = "dbo")]
    public class Leave
    {
        [Key]
        public Guid ID { get; set; }
        public float Hours { get; set; }
        public DateTime FromDate { get; set; }
        public int EmployId { get; set; }
        [MaxLength(250)]
        public String Comments { get; set; }
        [Column(TypeName="int")]
        public LeaveApproveStatus status { get; set; }
        [MaxLength(50)]
        public string Approver { get; set; }
    }
}

autoOffice/Models/Navbar.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace autoOffice.Models
{
    public class Navbar
    {
        public int Id { get; set; }
        public string nameOption { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
        public string area { get; set; }
        public string imageClass { get; set; }
        public string activeli { get; set; }
        public bool status { get; set; }
        public int parentId { get; set; }
        public bool isParent { get; set; }
    }
}

autoOffice/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace autoOffice.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "This is the home page of RC office OA 2015.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Leave() {
            ViewBag.Message = "Leave From";
            return View();
        }
    }
}

autoOffice/Controllers/LeaveController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using autoOffice.Models;

namespace autoOffice.Controllers
{
    public class LeaveController : Controller
    {
        private DbHelper db = new DbHelper();

        //
        // GET: /Leave/

        public ActionResult Index()
        {
            return View(db.Leaves.ToList());
        }

        //
        // GET: /Leave/Details/5

        public ActionResult Details(Guid id)
        {
            Leave leave = db.Leaves.Find(id);
            if (leave == null)
            {
                return HttpNotFound();
            }
            return View(leave);
        }

        //
        // GET: /Leave/Create

        public ActionResult Create()
        {
            db.Employees.Load();
            List<SelectListItem> items = new List<SelectListItem>();
            foreach(var item in db.Employees.Local){
                items.Add(new SelectListItem { Value = item.ID.ToString(), Text = item.MailAddress });
            }
            ViewData["approver"] = items;
            return View();
        }

        //
        // POST: /Leave/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Leave leave)
        {
            if (ModelState.IsValid)
            {
                leave.ID = Guid.NewGuid();
                db.Leaves.Add(leave);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(leave);
        }

        //
        // GET: /Leave/Edit/5

        public ActionResult Edit(Guid id )
        {
            Leave leave = db.Leaves.Find(id);
            if (leave == null)
            {
                return HttpNotFound();
            }
            return View(leave);
        }

        //
        // POST: /Leave/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Leave leave)
        {
            if (ModelState.IsValid)
            {
                db.Entry(leave).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(leave);
        }

        //
        // GET: /Leave/Delete/5

        public ActionResult Delete(Guid id )
        {
            Leave leave = db.Leaves.Find(id);
            if (leave == null)
            {
                return HttpNotFound();
            }
            return View(leave);
        }

        //
        // POST: /Leave/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Leave leave = db.Leaves.Find(id);
            db.Leaves.Remove(leave);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

autoOffice/Controllers/NavbarController.cs
using autoOffice.Common;
using autoOffice.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace autoOffice.Controllers
{
    public class NavbarController : Controller
    {
        // GET: Navbar
        public ActionResult Index()
        {
            var data = new Data();
            return PartialView("_Navbar", data.navbarItems().ToList());
        }
    }
}

autoOffice/Views/Employee/Create.cshtml
@model autoOffice.Models.Employee

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Employee</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MailAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MailAddress)
            @Html.ValidationMessageFor(model => model.MailAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Department)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Department)
            @Html.ValidationMessageFor(model => model.Department)
        </div>

        @*<div class="editor-label">
            @Html.LabelFor(model => model.LeaveReportTo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LeaveReportTo)
            @Html.ValidationMessageFor(model => model.LeaveReportTo)
        </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.LeaveReportTo)
        </div>
        <div style="width:200px">
            @Html.ListBoxFor(model => model.LeaveReportTo, (SelectList)ViewBag.LeaveReportTo, new {style = "width: 200px;" })
        </div>
        <p>
            <input type="submit" value="Create" />
        </p>
</fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

autoOffice/Views/Employee/Details.cshtml
@model autoOffice.Models.Employee

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Employee</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.MailAddress)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.MailAddress)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Department)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Department)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LeaveReportTo)
    </div>
    <div class="display-field">
        @ViewBag.LeaveReportTo.Name
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

autoOffice/Views/Employee/Edit.cshtml
@model autoOffice.Models.Employee

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Employee</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Name)
            @Html.ValidationMessageFor(model => model.Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.MailAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.MailAddress)
            @Html.ValidationMessageFor(model => model.MailAddress)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Department)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Department)
            @Html.ValidationMessageFor(model => model.Department)
        </div>

        @*<div class="editor-label">
            @Html.LabelFor(model => model.LeaveReportTo)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LeaveReportTo)
            @Html.ValidationMessageFor(model => model.LeaveReportTo)
        </div>*@

        <div class="editor-label">
            @Html.LabelFor(model => model.LeaveReportTo)
        </div>
        @*<div style="width:200px">
            @Html.ListBoxFor(model => model.LeaveReportTo, (SelectList)ViewBag.LeaveReportTo, new { style = "width: 200px;" })
        </div>*@
        <div style="width:200px">
            @Html.DropDownListFor(model => model.LeaveReportTo, (SelectList)ViewBag.LeaveReportToShow, new { style = "width: 200px;" })
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

autoOffice/Views/Employee/Index.cshtml
@model IEnumerable<autoOffice.Models.Employee>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@{if(ViewBag.hasAccess==false){
  <p>Only 
     user can list all employee, Access deny</p>
  }else{
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th style="width:200px">
            @Html.DisplayNameFor(model => model.MailAddress)
        </th>
        <th style="width:50px">
            @Html.DisplayNameFor(model => model.Department)
        </th>
        <th style="width:100px">
            @Html.DisplayNameFor(model => model.LeaveReportTo)
        </th>
        <th>Operation</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <p class="fa fa-user" style="height:5px"/>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Department)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LeaveReportName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

  }}

autoOffice/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

autoOffice/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

autoOffice/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper"style="margin-left:0px;margin-right:0px">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more...
            </p>
        </div>
    </section>
}
<h3>About try version OA system of RC XMN:</h3>
<ol class="round">
    <li class="one">
        <h5>What's the purpose?</h5>
        We build this platform for automation our manual work.</br>
        Leave form, employee info, contact info, etc..
    </li>

    <li class="two">
        <h5>development</h5>
        work still on going, contact bob for request raising
    </li>
</ol>

autoOffice/Views/Leave/Create.cshtml
@model autoOffice.Models.Leave


<script>
    $(document).ready(function(){
        $("#datepicker").datepicker();
    })
</script>
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Leave</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Hours)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Hours)
            @Html.ValidationMessageFor(model => model.Hours)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FromDate)
        </div>
        @*<div class="editor-field">
            @Html.EditorFor(model => model.FromDate)
            @Html.ValidationMessageFor(model => model.FromDate)
        </div>*@
        <input type="text" id="datepicker" />

        <div class="editor-label">
            @Html.LabelFor(model => model.EmployId)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EmployId)
            @Html.ValidationMessageFor(model => model.EmployId)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Comments)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Comments)
            @Html.ValidationMessageFor(model => model.Comments)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Approver)
        </div>
        @*<div class="editor-field">
            @Html.EditorFor(model => model.Approver)
            @Html.ValidationMessageFor(model => model.Approver)
        </div>*@

        @Html.DropDownListFor(m=>m.Approver,ViewData["approver"] as List<SelectListItem>,"NED")

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

autoOffice/Views/Leave/Index.cshtml
@model IEnumerable<autoOffice.Models.Leave>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Hours)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FromDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmployId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Comments)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Approver)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Hours)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FromDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmployId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Approver)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

autoOffice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh">
    <head>
        <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
        <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/ui-lightness/jquery-ui.min.css" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - R-C-O-A-B-0-2</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
       
        <script src="@Url.Content("~/bower_components/metisMenu/dist/metisMenu.min.js")"></script>
        <!-- Custom Theme JavaScript -->
        <script src="@Url.Content("~/Scripts/sb-admin-2.js")"></script>
        <script src="@Url.Content("~/Scripts/bootstrap.js")"></script>
        <link href="@Url.Content("~/bower_components/font-awesome/css/font-awesome.min.css")" rel="stylesheet" type="text/css" />
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title"><img src="~/Images/rc/rc.png" /></p>
                </div>
                <div class="float-right">
                    <section id="login">
                       你好，<span class="username">@User.Identity.Name</span>!
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Index", "Index", "Home")</li>
                            <li>@Html.ActionLink("Employee", "Employee", "/")</li>
                            <li style="display:none">@Html.ActionLink("About", "About", "Home")</li>
                            <li style="display:none">@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Leave", "Leave", "/")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        
        <div id="body" style="margin-left:auto;margin-right:auto">
            @RenderSection("featured", required: false)
            <section class=" main-content clear-fix">
                <div style="float:left;margin-right:30px">
                    @Html.Action("Index", "Navbar")
                </div>
                <div style="float:left">
                    @RenderBody()
                </div>
            </section>
        </div>
        
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - Powered by XMN TA Team</p>
                </div>
            </div>
        </footer>

        @*@Scripts.Render("~/bundles/jquery")*@
        @RenderSection("scripts", required: false)
    </body>
</html>

autoOffice/Views/Shared/_Navbar.cshtml
@model IEnumerable<autoOffice.Models.Navbar>

<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    
    <!-- /.navbar-top-links -->
    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                
                @foreach (var item in Model)
                {
                    if (item.isParent == false && item.parentId == 0)
                    {
                        <li><a href="@Url.Action(item.action, item.controller)"><i class="@item.imageClass"></i> @item.nameOption</a></li>
                    }
                    else
                    {
                        if (item.isParent == true)
                        {
                            <li>
                                <a href="#"><i class="@item.imageClass"></i> @item.nameOption<span class="fa arrow"></span></a>                          
                                <ul class="nav nav-second-level">
                                    @foreach (var child in Model.Where(p => p.parentId == item.Id))
                                    {
                                        if (child.controller == null)
                                        {
                                            <li><a href="#">@child.nameOption</a></li>
                                        }
                                        else
                                        {
                                        <li><a href="@Url.Action(child.action, child.controller)">@child.nameOption</a></li>
                                        }
                                    }
                                </ul>
                            </li>
                        }
                    }
                }
            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>